Fix frontend docker

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -1,39 +1,38 @@
 FROM node:24-alpine AS base
 
-# Install dependencies only when needed
-FROM base AS deps
 # Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
 RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
-# Install dependencies based on the preferred package manager
+# Install production dependencies
+FROM base AS deps
 COPY package.json package-lock.json* ./
 RUN \
-  if [ -f package-lock.json ]; then npm ci; \
+  if [ -f package-lock.json ]; then npm install --omit=dev; \
   else echo "Lockfile not found." && exit 1; \
   fi
 
-# Rebuild the source code only when needed
-FROM base AS builder
-WORKDIR /app
-COPY --from=deps /app/node_modules ./node_modules
-COPY . .
-
 # Build the Tanstack Start application
+FROM base AS builder
+COPY package.json package-lock.json* ./
+RUN \
+  if [ -f package-lock.json ]; then npm install; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+COPY . .
 RUN npm run build
 
 # Production image, copy all the files and run the server
 FROM base AS runner
-WORKDIR /app
-
 ENV NODE_ENV=production
 
 RUN addgroup --system --gid 1001 nodejs
 RUN adduser --system --uid 1001 tanstack
 
-# Copy the built application
-COPY --from=builder --chown=tanstack:nodejs /app/.output ./
-COPY --from=builder --chown=tanstack:nodejs /app/public ./public
+COPY --from=deps /app/node_modules ./node_modules
+COPY --from=builder /app/package.json ./package.json
+COPY --from=builder /app/.output ./.output
+COPY --from=builder /app/public ./public
 
 USER tanstack
 
@@ -42,5 +41,5 @@ EXPOSE 3000
 ENV PORT=3000
 ENV HOSTNAME="0.0.0.0"
 
-# Start the Tanstack Start server
-CMD ["node", "server/index.mjs"]
+# Start the Tanstack Start server (node .output/server/index.mjs)
+CMD ["npm", "run", "start"]
